image: python:2.7

build_wheel:
  variables:
    CI_DEBUG_TRACE: "true"
  before_script:
    - pip install --upgrade bumpversion
    - git config --global user.email "cedric.messiant@gmail.com"
    - git config --global user.name "Cédric Messiant"
    - git remote add github git@github.com:ecreall/flask-example.git
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - touch ~/.ssh/known_hosts
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh-keyscan -H github.com >> ~/.ssh/known_hosts
    - git fetch github
  script:
    - git checkout github/test-gitlab
    - bumpversion minor
    - git status
    - git diff
    - git push github HEAD/test-gitlab