stages:
  - test
  - build
  - integration
  - deploy
test:
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
  script: pytest
build:
  stage: build
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install --upgrade twine
    - pip install -r requirements.txt
  script:
    - python setup.py bdist_wheel
    - twine upload -u cedricmessiant dist/*
deploy:
  stage: deploy
  script:
    - ssh-agent
    - ssh ec2-user@54.197.34.60 pip install --upgrade hellobluenove
